/**
 * AI Service
 * Handles ONLY communication layer: explanations, meal suggestions, and motivational feedback
 * Does NOT generate plans - plans are generated by Rule Engine
 */

import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import OpenAI from 'openai';

export interface NutritionPlanExplanationInput {
  tdee: number;
  bmr: number;
  targetCalories: number;
  protein: number;
  fat: number;
  carbs: number;
  deficit: number;
  goal: string;
  estimatedWeeklyChange: number;
  userProfile: {
    age: number;
    weight: number;
    height: number;
    gender: string;
    activityLevel: string;
  };
}

export interface MealSuggestionInput {
  protein: number;
  fat: number;
  carbs: number;
  calories: number;
  mealsPerDay: number;
  dietaryPreferences?: string[];
  mealType?: 'breakfast' | 'lunch' | 'dinner' | 'snack';
}

export interface ProgressFeedbackInput {
  pattern: string;
  weightChange: number;
  weeklyWeightChange: number;
  expectedChange: number;
  currentWeight: number;
  goal: string;
  adjustment: number;
  reason: string;
  warnings: string[];
  subjective: {
    energyLevel?: number;
    hungerLevel?: number;
    stressLevel?: number;
  };
}

export interface AdjustmentExplanationInput {
  oldCalories: number;
  newCalories: number;
  oldMacros: { protein: number; fat: number; carbs: number };
  newMacros: { protein: number; fat: number; carbs: number };
  pattern: string;
  reason: string;
  weightChange: number;
  expectedChange: number;
}

@Injectable()
export class AIService {
  private openai: OpenAI;

  constructor(private configService: ConfigService) {
    const apiKey = this.configService.get<string>('OPENAI_API_KEY');
    if (!apiKey) {
      console.warn('OPENAI_API_KEY not set. AI features will be disabled.');
    }
    this.openai = new OpenAI({
      apiKey: apiKey || 'dummy-key',
    });
  }

  /**
   * Generate human-readable explanation of nutrition plan
   */
  async explainNutritionPlan(
    input: NutritionPlanExplanationInput,
  ): Promise<string> {
    const {
      tdee,
      bmr,
      targetCalories,
      protein,
      fat,
      carbs,
      deficit,
      goal,
      estimatedWeeklyChange,
      userProfile,
    } = input;

    const prompt = `You are a professional nutrition coach explaining a personalized nutrition plan to a client.

Client Profile:
- Age: ${userProfile.age}
- Weight: ${userProfile.weight}kg
- Height: ${userProfile.height}cm
- Gender: ${userProfile.gender}
- Activity Level: ${userProfile.activityLevel}
- Goal: ${goal}

Nutrition Plan (calculated by metabolic formulas):
- BMR (Basal Metabolic Rate): ${bmr} calories
- TDEE (Total Daily Energy Expenditure): ${tdee} calories
- Target Calories: ${targetCalories} calories
- Daily Macros: ${protein}g protein, ${fat}g fat, ${carbs}g carbs
- Energy Balance: ${deficit > 0 ? '+' : ''}${deficit} calories (${deficit > 0 ? 'surplus' : 'deficit'})
- Estimated Weekly Change: ${estimatedWeeklyChange > 0 ? '+' : ''}${estimatedWeeklyChange}kg

Write a warm, encouraging explanation (3-4 sentences) that:
1. Explains what TDEE is and how their ${targetCalories} calorie target was calculated
2. Explains why this deficit/surplus is safe and effective for their goal
3. Explains what to expect in terms of progress (${estimatedWeeklyChange}kg/week)
4. Provides one actionable tip for success

Use a friendly, conversational tone. Be specific about the numbers but keep it easy to understand.`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini',
        max_tokens: 300,
        temperature: 0.7,
        messages: [
          {
            role: 'system',
            content: 'You are a professional nutrition coach providing warm, encouraging explanations.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      return response.choices[0]?.message?.content || 'Explanation unavailable';
    } catch (error) {
      console.error('AI explanation error:', error);
      // Fallback to basic explanation
      return `Your personalized plan targets ${targetCalories} calories per day, calculated from your TDEE of ${tdee} calories with a ${Math.abs((deficit / tdee) * 100).toFixed(0)}% ${deficit < 0 ? 'deficit' : 'surplus'}. This safe approach should result in approximately ${Math.abs(estimatedWeeklyChange)}kg ${estimatedWeeklyChange < 0 ? 'loss' : 'gain'} per week. Focus on hitting your protein target of ${protein}g daily to preserve muscle mass.`;
    }
  }

  /**
   * Generate meal suggestions that fit macro targets
   */
  async suggestMeals(input: MealSuggestionInput): Promise<any[]> {
    const {
      protein,
      fat,
      carbs,
      calories,
      mealsPerDay,
      dietaryPreferences = [],
      mealType = 'lunch',
    } = input;

    const caloriesPerMeal = Math.round(calories / mealsPerDay);
    const proteinPerMeal = Math.round(protein / mealsPerDay);
    const fatPerMeal = Math.round(fat / mealsPerDay);
    const carbsPerMeal = Math.round(carbs / mealsPerDay);

    const prompt = `You are a professional meal planner. Suggest 3 simple, delicious ${mealType} ideas.

Target per meal:
- Calories: ~${caloriesPerMeal}
- Protein: ~${proteinPerMeal}g
- Fat: ~${fatPerMeal}g
- Carbs: ~${carbsPerMeal}g

Dietary restrictions: ${dietaryPreferences.length > 0 ? dietaryPreferences.join(', ') : 'None'}

For each meal, provide:
1. A catchy name
2. Simple ingredient list (5-8 items with amounts)
3. Brief prep instructions (2-3 sentences)
4. Approximate macros

Format as JSON array:
[
  {
    "name": "Meal Name",
    "description": "Brief description",
    "ingredients": ["200g chicken breast", "150g brown rice", "100g broccoli"],
    "instructions": "Cook chicken, prepare rice, steam broccoli. Season to taste.",
    "macros": { "calories": 450, "protein": 45, "fat": 8, "carbs": 48 }
  }
]

Keep meals realistic, affordable, and easy to prepare. Only return the JSON array, no other text.`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini',
        max_tokens: 1500,
        temperature: 0.8,
        response_format: { type: 'json_object' },
        messages: [
          {
            role: 'system',
            content: 'You are a professional meal planner. Always respond with valid JSON only.',
          },
          {
            role: 'user',
            content: prompt + '\n\nRespond with JSON object: {"meals": [...]}',
          },
        ],
      });

      const content = response.choices[0]?.message?.content;
      if (!content) return [];

      const parsed = JSON.parse(content);
      return parsed.meals || [];
    } catch (error) {
      console.error('AI meal suggestion error:', error);
      // Fallback to basic suggestions
      return [
        {
          name: 'Grilled Chicken & Rice',
          description: 'Classic high-protein meal',
          ingredients: [
            `${proteinPerMeal * 5}g chicken breast`,
            `${carbsPerMeal * 0.7}g brown rice`,
            '100g mixed vegetables',
          ],
          instructions:
            'Grill chicken, cook rice, steam vegetables. Season with herbs and spices.',
          macros: {
            calories: caloriesPerMeal,
            protein: proteinPerMeal,
            fat: fatPerMeal,
            carbs: carbsPerMeal,
          },
        },
      ];
    }
  }

  /**
   * Generate motivational progress feedback
   */
  async generateProgressFeedback(
    input: ProgressFeedbackInput,
  ): Promise<{ title: string; message: string }> {
    const {
      pattern,
      weightChange,
      weeklyWeightChange,
      expectedChange,
      currentWeight,
      goal,
      adjustment,
      reason,
      warnings,
      subjective,
    } = input;

    const prompt = `You are a supportive fitness coach giving feedback on a client's weekly check-in.

Progress Data:
- Pattern: ${pattern}
- Weight Change This Week: ${weightChange > 0 ? '+' : ''}${weightChange}kg
- Weekly Rate: ${weeklyWeightChange > 0 ? '+' : ''}${weeklyWeightChange}kg/week
- Expected Rate: ${expectedChange > 0 ? '+' : ''}${expectedChange}kg/week
- Current Weight: ${currentWeight}kg
- Goal: ${goal}
- Plan Adjustment: ${adjustment > 0 ? '+' : ''}${adjustment} calories
- Reason: ${reason}

Subjective Feedback:
- Energy Level: ${subjective.energyLevel || 'N/A'}/5
- Hunger Level: ${subjective.hungerLevel || 'N/A'}/5
- Stress Level: ${subjective.stressLevel || 'N/A'}/5

Warnings: ${warnings.length > 0 ? warnings.join(', ') : 'None'}

Generate a response in JSON format with:
{
  "title": "A short, punchy title (2-4 words) that captures the week's result",
  "message": "Motivational feedback (2-3 sentences) that acknowledges progress, explains what's happening, and encourages them"
}

Title examples based on patterns:
- "Outstanding Progress!" (on track, doing great)
- "Solid Week!" (good progress)
- "Keep Pushing!" (slight challenges but ok)
- "Adjusting Course!" (making needed changes)
- "Stay Strong!" (facing challenges)
- "Excellent Work!" (first check-in)

Message should be warm, encouraging, and professional. Be honest but supportive.

Return ONLY the JSON, no other text.`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini',
        max_tokens: 250,
        temperature: 0.7,
        messages: [
          {
            role: 'system',
            content: 'You are a supportive fitness coach providing motivational feedback.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      const content = response.choices[0]?.message?.content || '{}';

      // Clean markdown formatting if present (```json ... ```)
      let cleanedContent = content.trim();
      if (cleanedContent.startsWith('```')) {
        cleanedContent = cleanedContent.replace(/```json\n?/g, '').replace(/```/g, '').trim();
      }

      try {
        const parsed = JSON.parse(cleanedContent);
        return {
          title: parsed.title || 'Great Work!',
          message: parsed.message || 'Keep up the great work!',
        };
      } catch (parseError) {
        console.error('Failed to parse AI response:', cleanedContent);
        // If JSON parsing fails, return default
        return {
          title: 'Keep Going!',
          message: 'Great progress this week! Keep up the consistent effort.',
        };
      }
    } catch (error) {
      console.error('AI feedback error:', error);
      // Fallback to basic feedback
      if (pattern === 'on_track' || pattern === 'first_checkin') {
        return {
          title: 'Excellent Work!',
          message: `You're progressing exactly as expected with ${Math.abs(weeklyWeightChange)}kg ${weeklyWeightChange < 0 ? 'loss' : 'gain'} this week. Keep following your plan!`,
        };
      } else {
        return {
          title: 'Adjusting Course!',
          message: `Your progress is ${pattern.replace('_', ' ')}. I'm adjusting your calories by ${adjustment > 0 ? '+' : ''}${adjustment} to get you back on track. Stay consistent!`,
        };
      }
    }
  }

  /**
   * Explain why a plan adjustment was made
   */
  async explainAdjustment(
    input: AdjustmentExplanationInput,
  ): Promise<string> {
    const {
      oldCalories,
      newCalories,
      oldMacros,
      newMacros,
      pattern,
      reason,
      weightChange,
      expectedChange,
    } = input;

    const calorieChange = newCalories - oldCalories;

    const prompt = `You are a nutrition coach explaining a plan adjustment to a client.

Adjustment Details:
- Pattern Detected: ${pattern}
- Reason: ${reason}
- Weight Change: ${weightChange > 0 ? '+' : ''}${weightChange}kg
- Expected Change: ${expectedChange > 0 ? '+' : ''}${expectedChange}kg

Plan Changes:
- Calories: ${oldCalories} → ${newCalories} (${calorieChange > 0 ? '+' : ''}${calorieChange})
- Protein: ${oldMacros.protein}g → ${newMacros.protein}g
- Fat: ${oldMacros.fat}g → ${newMacros.fat}g
- Carbs: ${oldMacros.carbs}g → ${newMacros.carbs}g

Write a clear explanation (2-3 sentences) that:
1. Explains why the adjustment is being made (based on the pattern)
2. Explains what changed in their plan
3. Reassures them this is normal and part of the process

Tone: Professional, reassuring, educational.`;

    try {
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4o-mini',
        max_tokens: 200,
        temperature: 0.7,
        messages: [
          {
            role: 'system',
            content: 'You are a nutrition coach explaining plan adjustments clearly and professionally.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      return response.choices[0]?.message?.content || 'Your plan has been adjusted based on your progress.';
    } catch (error) {
      console.error('AI adjustment explanation error:', error);
      // Fallback to basic explanation
      return `Based on your progress, I'm ${calorieChange > 0 ? 'increasing' : 'decreasing'} your calories by ${Math.abs(calorieChange)} to ${newCalories} per day. Your protein stays at ${newMacros.protein}g to preserve muscle, while carbs and fats are adjusted proportionally. This adjustment will help you get back on track.`;
    }
  }
}
